apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\katar\Desktop\СТАЖИРОВКА\devops_tr\pro-module-05\my-app\book-service\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: mysql-users
  name: mysql-users
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-users
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\katar\Desktop\СТАЖИРОВКА\devops_tr\pro-module-05\my-app\book-service\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: mysql-users
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: users_db
            - name: MYSQL_ROOT_PASSWORD
              value: password
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: mysql-users
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-users-data
      restartPolicy: Always
      volumes:
        - name: mysql-users-data
          persistentVolumeClaim:
            claimName: mysql-users-data
