apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\katar\Desktop\СТАЖИРОВКА\devops_tr\pro-module-05\my-app\book-service\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\katar\Desktop\СТАЖИРОВКА\devops_tr\pro-module-05\my-app\book-service\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: DB_DSN
              value: root:password@tcp(mysql-users:3308)/users_db?charset=utf8&parseTime=True&loc=Local
          image: user-service
          imagePullPolicy: IfNotPresent
          name: user-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
